// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmsSfBT-0t0uCXbAPpXwFdHcpO3O3NRJ4',
    appId: '1:626525324491:android:18f5e88837b44aa697874e',
    messagingSenderId: '626525324491',
    projectId: 'mycalendar-970fe',
    storageBucket: 'mycalendar-970fe.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh3J2eomMoW3ecqyW_NXF0pjCBojc32Lg',
    appId: '1:626525324491:ios:9e20e3cc209f524397874e',
    messagingSenderId: '626525324491',
    projectId: 'mycalendar-970fe',
    storageBucket: 'mycalendar-970fe.firebasestorage.app',
    androidClientId: '626525324491-43rjos8826a55u2fqvtrt1ufpcf5n5sc.apps.googleusercontent.com',
    iosClientId: '626525324491-u4od0nddol11t5611pljduf94sdiedb2.apps.googleusercontent.com',
    iosBundleId: 'com.mycalendar.myCalendar',
  );
}
